// Generates src/fonts.generated.ts: a single TS module exporting a CSS
// string with the brand's fonts base64-embedded as @font-face rules.
//
// Why base64-embed instead of self-hosting via staticFile() + @remotion/
// fonts' loadFont() (or @remotion/google-fonts): those still fetch at render
// time and depend on delayRender()/continueRender() resolving correctly
// across every browser tab Remotion recycles during a long render. In
// resource-constrained/sandboxed environments that reproducibly hung on a
// tab-recycle boundary mid-render. Embedding the font as a data: URI in
// inline CSS removes the fetch entirely — the browser parses it
// synchronously from a string already in the page, so there's nothing to
// hang on, in any environment.
//
// Trade-off: src/fonts.generated.ts is checked into git, since regenerating
// it requires the @fontsource packages to be installed.
//
// RESKIN: to change fonts, `npm i @fontsource/<font>`, edit FONTS below so the
// `family` names match brand.fonts.headline / brand.fonts.body in your
// brands/*.json, then run `npm run fonts`.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const FONTS = [
  { family: "League Gothic", weight: "400", pkg: "@fontsource/league-gothic", file: "league-gothic-latin-400-normal.woff2" },
  { family: "Inter", weight: "500", pkg: "@fontsource/inter", file: "inter-latin-500-normal.woff2" },
  { family: "Inter", weight: "600", pkg: "@fontsource/inter", file: "inter-latin-600-normal.woff2" },
  { family: "Inter", weight: "700", pkg: "@fontsource/inter", file: "inter-latin-700-normal.woff2" },
  { family: "Inter", weight: "800", pkg: "@fontsource/inter", file: "inter-latin-800-normal.woff2" },
];

let css = "";
let ok = 0;
for (const f of FONTS) {
  const src = join(root, "node_modules", f.pkg, "files", f.file);
  if (!existsSync(src)) {
    console.warn(`[fonts] skipped ${f.pkg}/files/${f.file} — not found (is ${f.pkg} installed?)`);
    continue;
  }
  const b64 = readFileSync(src).toString("base64");
  css += `@font-face { font-family: '${f.family}'; font-weight: ${f.weight}; font-style: normal; font-display: block; src: url(data:font/woff2;base64,${b64}) format('woff2'); }\n`;
  ok++;
}

const target = join(root, "src", "fonts.generated.ts");
if (ok === 0 && existsSync(target)) {
  // Don't clobber a working checked-in file with an empty one (e.g. a
  // render-only environment where the @fontsource packages are missing).
  console.warn("[fonts] no font files found — keeping existing src/fonts.generated.ts");
} else {
  const out = `// AUTO-GENERATED by scripts/generate-fonts.mjs — do not edit by hand.
// Regenerate with \`npm run fonts\` after changing the FONTS list there.
export const FONT_FACE_CSS = ${JSON.stringify(css)};
`;
  writeFileSync(target, out);
  console.log(`[fonts] embedded ${ok}/${FONTS.length} fonts into src/fonts.generated.ts`);
}
